Test/ldg 304 klaytn app implement verifysignature in python t
blooo-io/LedgerHQ-app-klaytn pull request #9
Opened 2023-12-08 16:15 UTC by keiff3r

2023-12-08 16:25 UTC, Z4karia requested changes

2023-12-08 16:25 UTC, Z4karia commented on .vscode/settings.json
to remove

2023-12-08 16:25 UTC, Z4karia commented on .vscode/extensions.json
to remove

2023-12-08 16:25 UTC, Z4karia commented on Makefile
> +APPVERSION_M = 0
1.0.0

2023-12-12 14:38 UTC, keiff3r commented
The appropriate changes were made

2024-02-27 18:24 UTC, merged